In [ ]:
import torch

张量是计算的基本单位，可以简单理解为一个具有多个维度的数组。


In [2]:
x = torch.arange(0,6)
x

tensor([0, 1, 2, 3, 4, 5])

可以使用.shape来获取张量的形状

In [3]:
x.shape

torch.Size([6])

使用numel()获取元素数量

In [4]:
x.numel()

6

要改变张量的形状而不改变元素值和元素数量，可以调用reshape

In [6]:
x = x.reshape(2, 3)
x

tensor([[0, 1, 2],
        [3, 4, 5]])

创建全0、全1、或者特定分布随机采样的张量

In [12]:
y = torch.zeros(2, 3)
z = torch.ones(2, 3)
y,z

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]))

常见的加减乘除,乘方都将升级为按元素运算


In [13]:
y + z

tensor([[1., 1., 1.],
        [1., 1., 1.]])

也可以吧